const FETCH_TRANSCRIPT_REQ = 'FETCH_TRANSCRIPT_REQ'
const FETCH_TRANSCRIPT_SUCCESS = 'FETCH_TRANSCRIPT_SUCCESS'
const FETCH_TRANSCRIPT_ERROR = 'FETCH_TRANSCRIPT_ERROR'

// Created types for various actions and export it for further usage
export {FETCH_TRANSCRIPT_REQ,FETCH_TRANSCRIPT_SUCCESS,FETCH_TRANSCRIPT_ERROR}